name: Notify RP Channel

on:
  release:
    types: [published]

jobs:
  github-releases-to-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: GitHub Releases to Discord
        uses: SethCohen/github-releases-to-discord@v1
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          color: "4173298"
          username: "Resource Packs Releases"
          avatar_url: "https://i.ibb.co/GQ5JNKrn/logo-2.png"
          content: ""
          footer_title: "GhibliCraft - Releases"
          reduce_headings: true
          footer_timestamp: true
