name: Resource Pack Validator

on: [push, pull_request]

jobs:
  validate-resource-pack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: RESOURCE PACK VALIDATION - European
        uses: MrKinau/ResourcePackValidator@v1
        with:
          resourcepack: resource-packs/european/
          config: .github/workflows/config/resource-pack-validator.json
      
      - name: RESOURCE PACK VALIDATION - Japanese
        uses: MrKinau/ResourcePackValidator@v1
        with:
          resourcepack: resource-packs/japanese/
          config: .github/workflows/config/resource-pack-validator.json

      - name: RESOURCE PACK VALIDATION - Cosmetics
        uses: MrKinau/ResourcePackValidator@v1
        with:
          resourcepack: resource-packs/cosmetics/
          config: .github/workflows/config/resource-pack-validator.json